version: "3.9"
services:
  database:
    image: mariadb:latest
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./docker/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/database/data:/var/lib/mysql

  nginx:
    build:
      context: ./docker/nginx
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - '.:/var/www/current/'
      - './docker/nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './docker/nginx/sites/:/etc/nginx/sites-available'
      - './docker/nginx/conf.d/:/etc/nginx/conf.d'
    links:
      - php-fpm

  php-fpm:
    build:
      context: ./docker/php
    depends_on:
      - database
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}
    volumes:
      - '.:/var/www/current/'
    working_dir: '/var/www/current'
